<?php

return [

    /* all site location varaible */
    // menu options 
    'home'          => 'خانه ',
    'highlights'    => 'نکات برجسته',
    'courses'       => 'دوره های آموزشی',
    'enroll'        => 'ثب نام ',
    'certification' => 'شهادت نامه',
    'instruction'   => 'دستورالعمل',
    'contact'       => 'ارتباط با ما',
    'click_for_admission' => 'برای ثبت نام لینک ذیل را انتخاب کنید',
    'enroll_details' => 'TechLiteracy provides hundreds of digital literacy courses you can enroll. Please, fill out course enrollment form below to attend your desired courses. Our courses are cost-effective and are taught by highly qualified instructors using advanced methodology and state-of-the-art technologies.',
    'about_us'  => 'درباره ما',
    'about_details'  => 'TechLiteracy is a Digital Literacy Campaign, across female schools in Afghanistan. The aim of TechLiteracy is to bring resources for women and girls to gain new skills and become employable and productive members of the digital world-- digital literacy serves as the backbone of e-governance. 

        Participants of the campaign will include female citizens, aged 15-35, with little to no experience in computing or digital literacy. Through engaging with us the participants will develop a fundamental understanding of digital technologies (computers, mobile, hardware, software, Internet, tools and applications). This will be done through training, coaching and education programs across schools in Afghanistan. 

        TechLiteracy is managed by TechNation, a Kabul-based company focusing on technology, innovation, education and community. TechNation is invites diverse stakeholders to partner in the program design and implementation.',
    'background'        => 'تجارب',
    'team'  =>          'گروه کاری',
    'team_details'      => 'TechLiteracy is managed by top-notch national and international industry leaders, educationists, technology professionals, and government officials who have many years of experience in education, policy, technology, management and leadership.',
    'streeing_commitee'     => 'کمیته اجرایی',
    'partners'  =>      'همکاران ما',
    'prgram_by' =>      'برنامه سواد دیجیتالی برنامه ریزی شده توسط:',
    'technation_intro'  => 'معلوات در باره تکنشن',
    'in_partnership_with'       => 'در مشارکت با ',
    'teaching_method'           => 'روش تدریس',
    'methology_details'         => 'The TechLiteracy program’s digital competencies will include essential skills development in:',
    'method1'            => 'مدیریت اطلاعات',
    'method2'            => 'ارتباطات و همکاری',
    'method3'            => 'رسانه های دیجیتالی',
    'method4'            => 'استفاده ابزار دیجیتالی به خاطر آموزش',
    'method5'            => 'مدیریت انترنت',
    'after_method_text1'  => 'These competencies will enable learners with the means to access, evaluate and analyse and hence make an informed choice from a range of available data and information sources. It will enable learners to learn to communicate, collaborate and network with others. It will enhance their skills to analyse messages mediated by digital media, and will enable them to express themselves creatively across a range of digital media. Participants will gain competences in using digital tools in various media and in different modes of learning (autonomous, collaborative, exploratory, designing). The skills TechLiteracy will be teaching are necessary to become sophisticated users of  computers, essential tools and applications, and online resources.',
    'after_method_text2'  => 'Gaining these skills and competencies will help the program participants to become productive at home and at work. They will learn how to be responsible and competent in managing the internet, how to stay safe and secure online, how to make informed choices over privacy, how to respect intellectual property, what it takes to abide by terms and conditions of systems they use and respect the rights and feelings of others, and know how to use technology to complement work and lifestyle. They will be able to consider careers where one can put their skills to work.',

    'latest_courses' => 'آخرین دوره ها',
    'last_name'         => 'تخلص',
    'first_name'        => 'نام',
    'id_type'           => 'نوع شماره شناسایی',
    'id'                => 'شماره شناسایی',
    'select_course'     => "دوره های انتخابی",
    'fees_to_be_paid'   => "مجموعه فیس قابل پرداخت",
    'payment_details'   => "جزئیات پرداخت پول",
    'dob'               => "تاریخ تولد",
    'email'             => "پست الترونیکی",
    'phone'             => "تلیفن",
    'address'           => "آدرس",
    'emergency_contact' => "شماره تماس اضطراری",
    'education_background' => "سوابق تحصیلی",
    'dg_background'        => "سوابق در بخش کامپیوتر ",
    'language'             => "مهارت های زبانی",
    'alternative_phone'    => 'شماره تماس دیگر',
    'statment_of_purpose'  => 'هدف از ',
    'institute_name'       => 'نام مؤسسه',
    'your_contribution'    => 'مشارکت دانشجویی',
    // WIE application form options translation
    'about_wie'             => '',
    'personal_information'  => 'معلومات شخصی',
    'full_name'             => 'نام مکمل',
    'father_name'           => 'نام پدر',
    'gender'                => 'جنسیت',
    'male'                  => 'مذکر',
    'female'                => 'مؤثت',
    'age'                   => 'سن',
    'email_address'         => 'آدرس الکترونیکی',
    'mobile_cell_phone'     => 'شماره تماس/ شماره همراه',
    'wie_notice'            => 'برای پروژه زنان در اقتصاد فقط فرم های قابل قبول است که از افغانستان ثبت شده باشد و سن متقاضی بین 16 تا سی سال باشد',
    'education_and_job_search'  => 'تحصیلات و کارجویی',
    'current_student'           => 'آیا شاگرد برحال هستید',
    'highest_level_of_education' => 'بالاترین درجه تحصیلی شما چیست?',
    'levels_of_education'        => 'سطح تحصیل',
    'elementary'                 => 'ابتدائی(صنف 0 تا 5)',
    'middle_school'              => 'متوسطه(6-8) ',
    'high_school'                => 'لیسه (9-12) ',
    'university'                 => 'پوهنتون( لیسانسه) ',
    'master'                     => 'ماستر',
    'phd'                        => 'دکتورا',
    'other_education'            => 'آیا از دیگر نوع دوره های آموزشی قبلا مستفید شده اید؟ اگر بلی لطفاانتخاب کنید و در غیر آن صورت از این مرحله رد شوید  ',
    'business_private_company'   => 'تجارت / کارشخصی',
    'tvet'                       => 'تی وی ای تی(موسسه)',
    'employer_on_the_job_training' => 'کار فرما در دوره های آموزش شغلی',
    'other'                        => 'دیگر',
    'notice2'                      => 'نوع برنامه و محل برگزاری برنامه را با استفاده از گزینه های انتخابی مشخص کنید',
    // why are you registering with women in the economy section options
    'why_you_register'             => 'چرا در پروژ] زنان و اقتصاد ثبت نام کردید؟ ',
    'find_a_new_job'               => 'به خاطر پیدا نمودن شغل جدید',
    'internship'                   => 'برای شرکت در دوره های کار آموزی',
    'participate_training'         => 'برای پیشرفت دادن حرفه خود و اشتراک در دوره های آموزشی',
    'scholarship'                  => 'برای درخواست کمک هزینه تحصیلی',
    // types of job options
    'what_type_of_job'             => 'چی نوع شغلی مورد قبول شما میباشد؟ ( لطفا تمام گزینه ها را بررسی کنید)',
    'full_time'                    => 'تمام وقت',
    'part_time'                    => 'نیمه وقت',
    'self_employed'                => 'کارآفرین/ شغل آزاد',
    'internship_office'            => 'کار آموزی(در یک اداره)',
    'temporary'                    => 'مؤقتی/( فصلی)',
    'apprenticeship'               => 'کار آموزی( در بخش تجارت)',
    'volunteer'                    => 'خدمات داوطلبانه( به نفع جامعه)',
    //level of job options
    'what_level_of_job'            => 'کدام نوع کار مطابقت با تجارب کاری شما دارد؟',
    'entry_level'                  => 'در سطح ورود به یک مؤسسه(0 سال)',
    'junior'                       => 'تازه کار(1-3 سال)',
    'mid_level'                    => 'سطح متوسط(4-5 سال) ',
    'senior'                       => 'بالاتر از (5 سال)',
    // when would you available to start work (options)
    'when_start_work'              => 'بعد از چی مدت آمده به کار خواهید بود؟',
    'three_months'                 => 'یک تا سه ماه',
    'four_months'                  => '4 تا 6 ماه',
    'one_year'                     => 'یک سال',
    'other-date'                   => 'اگر در غیر تاریخ های ذکر شده است(لطفا مشخصاً بنویسید)',
    // How many years do you plan to work (options)
    'work_plan_time'               => 'مدت چند سال پلان دارید که کار کنید؟',
    'less_than_one_year'           => 'کمتر از یک سات',
    'two_years'                    => '2- 3 سال',
    'four_years'                   => '4-5 سال',
    'six_years'                    => '6-7 سال',
    'seven_years'                  => 'زیادتر از 7 سال',
    'family_support'               => 'آیا از تصمیم شما فامیل پشتیبانی میکنند؟',
    'yes'                          => 'بلی',
    'no'                           => 'نخیر',
    // number of females in family options
    'number_of_females_in_family'  => 'چی تعداد از خانم ها در فامیل تان مصروف کار بودند و هستند؟',
    'none'                         => 'هیچ ',
    'one'                          => '1',
    'two'                          => '2',
    'more'                         => 'اگر تعداد شان بیشتر از لیست ذکر شده است (لطفا مشخص کنید؟)',
    // follow up questionnaire
    'follow_up_qes'                => 'پیگیری پرسشنامه ',
    'other-contact_info'           => 'معلومات ارتباطی اضافه تر',
    'current_home_add'             => 'آدرس فعلی خانه ',
    'emergency_contact_wie'        => 'شماره تماس اضطراری(از یکی از اعضای خانواده)',
    'neighborhood'                 => 'محله',
    'district'                     => 'ولسوالی',
    'province'                     => 'ولایت',
    // Educational information options
    'educational_information'      => 'اطلاعات تحصیلی',
    'high_school_edu'              => 'لیسه',
    'university_edu'               => 'پوهنتون(لیسانسه)',
    'university_master'            => 'ماستر',
    'name_of_school'               => 'مکتب/دانشکده/ دانشگاه',
    'city_location'                => 'شهر، موقعیت، کشور',
    'area_of_study'                => 'محل تحصیل/ رشته تحصیلی',
    'start_date'                   => 'تاریخ شروع',
    'end_date'                     => 'تاریخ ختم',
    'graduated'                    => 'فارغ شده',
    // Employment Information options
    'employment'                   => 'استخدام',
    'are_you_currently_employed'   => 'آیا در حال حاضر شاغل هستید؟',
    'if_yes'                       => 'اگر بلی، مصروف چی شغلی میباشید؟ (گزینه های انتخابی را با دقت انتخاب کنید) در صورت جواب خیر از این مرحله بگزرید',
    'work_experience'              => 'آیا دارای تجارب کاری میباشید؟ اگر بلی، لطفا جدولی را که مربوط تجارب کاری میباشد را خانه پری نمائید و سی وی خود را ضمیمه کنید. اگر جواب تان خیر است از این مرحله رد شوید.',
    'company_name'                 => 'نام شرکت/ کارفرما',
    'city_or_location'             => 'شهر یا موقعیت',
    'position'                     => 'موقعیت کاری و یا عنوان وظیفه تان',
    'profession'                   => 'حرفه',
    'sector'                       => 'بخش کاری شما',
    'key_responsibilities'         => ' مسئولیت های  اصلی ',
    // work experience options
    'work_experience_years'        => 'مجموعه تجارب کاری شما?',
    'entry_level_0'                => 'در سطح کار آموزی(0-1 سال)',
    'junior_level_1'               => 'ابتدایی(1-3 سال)',
    'mid_level_4'                  => 'سطح متوسط(4- 5 سال)',
    'senior_level_5'               => 'سطح ارشد(بالاتر از 5 سال)',
    //job seeker (for all enrollments) options
    'job_seekers'                  => 'جستجو کننده کار',
    'industry_interested_work'     => 'در کدام صنعت علاقه مند به کار هستید؟',
    'Private_sector_business'      => 'تجارت در بخش خصوصی',
    'banking_and_finance'          => 'بخش مالی و تجارت',
    'government'                   => 'در بخش های دولتی',
    'healthcare'                   => 'مراقبت های بهداشتی',
    'ict'                          => 'آی سی تی',
    'food_processing'              => 'تجارت کشاورزی/ فرآوری مواد غذایی',
    'own_business'                 => 'تجارت شخصی/ شغل آزاد',
    'education_section'            => 'بخش های تحصیلی',
    'other_specify'                => 'آگر کدام بخش دیگری میباشد (لطفا مشخصاً ذکر کنید)',
    // expected salary range
    'expected_salary'              => 'معاش تقاضا شده شما بین کدام حدود میباشد(افغانی)',
    'entry_level_range'            => 'در حد معاش ابتدایی',
    'mid_level_range'              => 'متوسط',
    'senior_level_range'           => 'بالاترین حد ',
    // entrepreneurship options
    'entrepreneurship'             => 'کارآفرینی/ ایجاد شغل',
    'start_your_own_business'      => 'آیا دوست دارید از خود تجارت شخصی داشته باشید و یا دارای شغل آزاد باشید؟',
    'yes_i_think'                  => 'اگر بلی به کدام دوره های آموزشی و ظرفیت سازی ضرورت دارید؟ ',
    'business_skill'               => 'مهارت های تجاری',
    'soft_skill'                   => 'مهارت در بخش نرم افزار سازی',
    'book_keeping'                 => 'دفتر داری',
    'business_management'          => 'مدیریت تجارت',
    'accounting'                   => 'حسابداری/ مالی',
    'sales'                        => 'فروشات',
    'administrative_skills'        => 'مهارت های اداری',
    'human_resource'               => 'منابع بشری',
    'marketing'                    => 'بازار یابی',
    'networking'                   => 'شبکه های کمپیوتری',
    'negotiation'                  => 'مذاکرات',
    'customer_relation'            => 'ارتباط با مشتری',
    'problem_solving'              => 'راه حل باری مشکلات',
    'creativity'                   => 'خلاقیت و نو آوری',
    'communication'                => 'ارتباطات',
    'time_management'              => 'مدیریت زمان',
    // Technical Trainings

    'technical_training'           => 'آموزش های حرفه ای',
    'need_of_technical_training'   => 'آیا کدام آموزش و یا سرتفیکت مشخصلی است که شما به خاطر ورود به شغل مورد نظر خود به آن نیازمند باشید؟',
    'if_no_skip'                   => 'اگر بلی، لطفا به صورت مشخص بنویسید در غیر آن صورت از این مرحله بگذرید.',
    // motivational statement options
    'motivational_statement'       => 'بیانیه انگیزشی',
    'motivation_wants'             => 'علت انگزیزه اشتراک خود را در این برنامه با ما در میان بگذارید.(بیشتر از یک پاراگراف نباشد.)',
    // Time availability
    'time_availability'            => 'موجودیت زمانی',
    'time_form_label'              => 'چی مدت زمان را در طول یک هفته صرف تحصیل و جستجوی وظیفه مینمایید؟?',
    'noting'                       => 'هیچ ',
    // Access to financial resources
    'access_to_financial_res'      => 'دسترسی به منابع مالی',
    'financial_res_label'          => 'چقدر منابع مالی را به خاطر پیشرفت شغلی و جستجوی کار خود به مصرف رساندید؟',




];
